#!/bin/sh
[ "$1" == 'start' ] || exit 0

#getty -L 3000000 ttyS2

sed -i '/^sd/d' /etc/mdev.conf
/etc/init.d/S10mdev restart
mount -o rw,noatime,nodev /dev/sda2 /media/creality/sda2
umount /usr/deplibs
mount -o bind /media/creality/sda2/deplibs /usr/deplibs
umount /usr/data
mount -o bind /media/creality/sda2/data /usr/data

umount /usr/apps
mount -o bind /media/creality/sda2/apps /usr/apps

mount | grep /dev/mmcblk0 && poweroff

#ps > /tmp/ps.txt
#lsof > /tmp/lsof.txt
#mount -o remont,rw /media/creality/sda1
for f in /usr/apps/etc/init.d/S*; do "$f" start; done

exit 0
