#!/bin/sh
[ "$1" == 'start' ] || exit 0

#getty -L 3000000 ttyS2

sed -i '/^sd/d' /etc/mdev.conf
/etc/init.d/S10mdev restart

umount /usr/deplibs
mount -o rw,noatime,nodev /dev/sda2 /usr/deplibs

umount /usr/apps
mount -o rw,noatime,nodev /dev/sda3 /usr/apps

umount /usr/data
mount -o rw,noatime,nodev /dev/sda4 /usr/data

mount | grep /dev/mmcblk0 && poweroff

#ps > /tmp/ps.txt
#lsof > /tmp/lsof.txt
#mount -o remont,rw /media/creality/sda1
for f in /usr/apps/etc/init.d/U*; do 
	echo "Starting: `date` $f" >> /tmp/startup.log
	"$f" start
done

exit 0
